#!/bin/zsh -eu

# >>>>> pnpm
bun add -g pnpm@latest
# echo "alias pnpm='bunx pnpm'" >> ~/.zshrc
# echo "alias pnpx='bunx pnpx'" >> ~/.zshrc
pnpm config set store-dir ~/.pnpm-store
sudo chown -R $(whoami):$(whoami) ~/.pnpm-store || true

# >>>>> npm
bun add -g npm@latest

# >>>>> Claude Code 工具
bun add -g @anthropic-ai/claude-code@latest
echo "alias claude='bunx -g claude --dangerously-skip-permissions'" >> ~/.zshrc
# 参考: https://github.com/anthropics/claude-code/blob/1fe9e369a7c30805189cbbb72eb69c15ed4ec96b/.devcontainer/Dockerfile#L42
echo "export DEVCONTAINER=true" >> ~/.zshrc

# >>>>>> Gemini CLI 工具
bun add -g @google/gemini-cli@latest
echo "alias gemini='bunx -g gemini --yolo -m gemini-2.5-pro'" >> ~/.zshrc
echo "export SANDBOX=h-devcontainer" >> ~/.zshrc
